### ISSUE TITLE
Add the possibility of selecting environment

### ISSUE THREAD

**Issue by jasalguero** [kiwiupover/ember-cli-surge#16]
It would be great to be able select the target environment, so if you are using for example ember Mirage, you can choose if you want the mock api to work (basically making it a great prototype tool to share with other people) or have a more production version released

**Comment by kiwiupover** [comment]
Yes I agree @jasalguero 

I don't think it would be very difficult to do. I would welcome a PR. 

I working on fixing up the tests at the moment then I want to add all the surge cli commands. 

Cheers

**Comment by kiwiupover** [comment]
@jasalguero I justed out a fix for you can you let me know if you have any issues.

**Comment by sheriffderek** [comment]
Just as a note to future visitors, I also wondered about this:

`ember surge --environment development`
