### ISSUE TITLE
200 OK

### ISSUE THREAD

**Issue by oskarrough** [kiwiupover/ember-cli-surge#3]
Hi, thanks for this shortcut! Not sure where to add the code in this project, but if you do:

`mv dist/index.html dist/200.html`

before deploying, ember will catch all requests. See http://surge.sh/help/adding-a-200-page-for-client-side-routing

**Comment by kiwiupover** [comment]
The 200.htlm to the public folder. It will be moved to the dist folder at build time. 

Cheers

**Comment by mphasize** [comment]
@kiwiupover I think his suggestion was to copy/move the `dist/index.html` to `dist/200.html` *after* the build has finished and *before* triggering the surge deployment. That way we should be able to use Ember's `location` or auto routing instead of hash-based routing and get much nicer URLs.

**Comment by mphasize** [comment]
Just created a PR for this https://github.com/kiwiupover/ember-cli-surge/pull/6

**Comment by oskarrough** [comment]
@mphasize exactly, thanks!
