### ISSUE TITLE
How to use "--new-domain" command ?

### ISSUE THREAD

**Issue by hugoruscitti** [kiwiupover/ember-cli-surge#40]
Hi!, i'm working in a project that needs to publish two branches to surge, one for develop and other for master.

I think the "--new-domain" allows me to publish the same project to separated domains, and i make some scripts to auto-deploy on travis.

But i ends up thinking that i'm misunderstood the use of the "--new-domain" usage: 

![pilas-bloques - travis ci 2016-10-06 10-16-42](https://cloud.githubusercontent.com/assets/99183/19153722/08ee40ba-8bae-11e6-8a48-e039ab6cce88.png)

there are any example of change domain to deploy based on current branch, or some like that from travis?

Thanks!

**Comment by kiwiupover** [comment]
@hugoruscitti I have had a look and it seems is a bug I will have an update this week.

Thanks for reporting it!

**Comment by kiwiupover** [comment]
Thanks @hugoruscitti I just pushed an update that fixes your issue. Thanks heaps, for reporting the problem. 

Fixed by #43

**Comment by hugoruscitti** [comment]
Thanks @kiwiupover  !!!!

**Comment by kiwiupover** [comment]
Glad to help! Let me know how it turns out.

**Comment by hugoruscitti** [comment]
Thanks @kiwiupover !!!!

Works great with the new version 1.1.13!!!, i use it in two projects, to deploy automatically from travis. Thanks again!!!

- https://github.com/Program-AR/pilas-bloques/blob/develop/.travis.yml#L35
- https://github.com/Program-AR/pilas-bloques-jr/blob/master/.travis.yml#L28
