### ISSUE TITLE
Using `ember-cli-surge` Tavis builds don't pick up on ENV vars

### ISSUE THREAD

**Issue by mphasize** [kiwiupover/ember-cli-surge#7]
I just tried to use `ember surge` on Travis ( following this guide https://surge.sh/help/integrating-with-travis-ci ) to enable automatic deployments on successful builds, but the command is unable to read the ENV vars. (Means that surge is asking me for username/password)

I attempted to fix it, by explicitly passing the ENV from the master process (see https://github.com/mphasize/ember-cli-surge/tree/env-vars) but that's not working either.

Running the `surge` command directly on Travis, the login details are picked up from `SURGE_LOGIN` and `SURGE_TOKEN` without any problems.

Any ideas what could cause this?

**Comment by kennethormandy** [comment]
Hey! My guess is because this addon is still running Surge v0.12.0. We didn’t add `--token` and proper environment variable support until v0.13.0, and we are on v0.14.3 now. I opened up a PR that should fix this.

**Comment by kiwiupover** [comment]
@mphasize I have just added the command `ember surge --token` which you can use with to get the auth token.  Use the token for as an environment variable with travis. 

Environment variables:

SURGE_LOGIN: Set it to the email address you use with Surge
SURGE_TOKEN: Set it to your login token (get it by doing a surge token)

In your `.travis.yml` add 

```
after_success:
     - ember surge
```

I have not tested this myself yet.

**Comment by kiwiupover** [comment]
This is good to go!
