### ISSUE TITLE
Transfer ownership / add Surge team as maintainers?

### ISSUE THREAD

**Issue by kennethormandy** [kiwiupover/ember-cli-surge#9]
Hey @kiwiupover,

Would you be open to transferring this repository to the @surge-sh organisation, and/or adding @sintaxi and @kennethormandy (me) as collaborators and giving us access to publish releases on npm?

We’d really like to keep improving the experience of using Surge together with Ember. We can give this integration more active attention if we know we can publish releases ourselves (similarly to how we maintain the Grunt plugin for Surge).

Let me know what you think. Thanks so much for getting this started and keeping it going. It’s appreciated!

**Comment by kiwiupover** [comment]
Cheers @kennethormandy for getting in contact tonight. Tomorrow night I speaking at the Seattle Ember JS meetup about deployment and I was going to start with show how simple it is to deploy an ember app to surge. 

I have added you guys as collaborators here and at NPM. We can talk about moving down this repo under the surge-sh org the road a bit.

Cheers 
Dave

**Comment by kennethormandy** [comment]
Awesome! Thanks so much. As long as you’re still on board to lead and maintain it, that totally works for us. We actually have a new release of Surge we’re putting together right now that should make integrations like this more powerful and easier to maintain, so I’ll follow up with you with that documentation soon.

I wish we knew about the meetup, we’ll try and get you some stickers in time for your next talk! I hope it goes well, and let us know if there’s a video we can check out afterwards or a link we can share out.

**Comment by kiwiupover** [comment]
Marvelous, looking forward to seeing what is in store for surge.sh project. 

I would love to have stickers on hand for tonight but hey, next time. 

Cheers
Dave



-- 
Dave Laird
Sent with Airmail

On October 28, 2015 at 11:18:55 AM, Kenneth Ormandy (notifications@github.com) wrote:

Awesome! Thanks so much. As long as you’re still on board to lead and maintain it, that totally works for us. We actually have a new release of Surge we’re putting together right now that should make integrations like this more powerful and easier to maintain, so I’ll follow up with you with that documentation soon.

I wish we knew about the meetup, we’ll try and get you some stickers in time for your next talk! I hope it goes well, and let us know if there’s a video we can check out afterwards or a link we can share out.
